type: chart
rootfs:
  - image: samsung_cnct/cluster-controller
    context: cluster-controller
    chart: cluster-controller
    value: image.name
    dockerContext: .
configs:
  - chart: cluster-controller
    timeout: 600
    retries: 2
    release: cluster-controller
test:
  beforeScript:
    image: golang:1.8.3
    shell: /bin/bash
    script: ./pipeline_wrapper_verify.sh
prod:
  doDeploy: none
