// +build !ignore_autogenerated

/*
Copyright 2018 Samsung CNCT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudProviderCredentials) DeepCopyInto(out *CloudProviderCredentials) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudProviderCredentials.
func (in *CloudProviderCredentials) DeepCopy() *CloudProviderCredentials {
	if in == nil {
		return nil
	}
	out := new(CloudProviderCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudProviderInfo) DeepCopyInto(out *CloudProviderInfo) {
	*out = *in
	out.Credentials = in.Credentials
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudProviderInfo.
func (in *CloudProviderInfo) DeepCopy() *CloudProviderInfo {
	if in == nil {
		return nil
	}
	out := new(CloudProviderInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInfo) DeepCopyInto(out *ClusterInfo) {
	*out = *in
	out.Fabric = in.Fabric
	if in.NodePools != nil {
		in, out := &in.NodePools, &out.NodePools
		*out = make([]NodeProperties, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInfo.
func (in *ClusterInfo) DeepCopy() *ClusterInfo {
	if in == nil {
		return nil
	}
	out := new(ClusterInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricInfo) DeepCopyInto(out *FabricInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricInfo.
func (in *FabricInfo) DeepCopy() *FabricInfo {
	if in == nil {
		return nil
	}
	out := new(FabricInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrakenCluster) DeepCopyInto(out *KrakenCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrakenCluster.
func (in *KrakenCluster) DeepCopy() *KrakenCluster {
	if in == nil {
		return nil
	}
	out := new(KrakenCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrakenCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrakenClusterList) DeepCopyInto(out *KrakenClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrakenCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrakenClusterList.
func (in *KrakenClusterList) DeepCopy() *KrakenClusterList {
	if in == nil {
		return nil
	}
	out := new(KrakenClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrakenClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrakenClusterSpec) DeepCopyInto(out *KrakenClusterSpec) {
	*out = *in
	out.CloudProvider = in.CloudProvider
	out.Provisioner = in.Provisioner
	in.Cluster.DeepCopyInto(&out.Cluster)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrakenClusterSpec.
func (in *KrakenClusterSpec) DeepCopy() *KrakenClusterSpec {
	if in == nil {
		return nil
	}
	out := new(KrakenClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrakenClusterStatus) DeepCopyInto(out *KrakenClusterStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrakenClusterStatus.
func (in *KrakenClusterStatus) DeepCopy() *KrakenClusterStatus {
	if in == nil {
		return nil
	}
	out := new(KrakenClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeProperties) DeepCopyInto(out *NodeProperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeProperties.
func (in *NodeProperties) DeepCopy() *NodeProperties {
	if in == nil {
		return nil
	}
	out := new(NodeProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionerInfo) DeepCopyInto(out *ProvisionerInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionerInfo.
func (in *ProvisionerInfo) DeepCopy() *ProvisionerInfo {
	if in == nil {
		return nil
	}
	out := new(ProvisionerInfo)
	in.DeepCopyInto(out)
	return out
}
