/*
Copyright 2018 Samsung CNCT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/samsung-cnct/cluster-controller/pkg/apis/clustercontroller/v1alpha1"
	scheme "github.com/samsung-cnct/cluster-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KrakenClustersGetter has a method to return a KrakenClusterInterface.
// A group's client should implement this interface.
type KrakenClustersGetter interface {
	KrakenClusters(namespace string) KrakenClusterInterface
}

// KrakenClusterInterface has methods to work with KrakenCluster resources.
type KrakenClusterInterface interface {
	Create(*v1alpha1.KrakenCluster) (*v1alpha1.KrakenCluster, error)
	Update(*v1alpha1.KrakenCluster) (*v1alpha1.KrakenCluster, error)
	UpdateStatus(*v1alpha1.KrakenCluster) (*v1alpha1.KrakenCluster, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.KrakenCluster, error)
	List(opts v1.ListOptions) (*v1alpha1.KrakenClusterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KrakenCluster, err error)
	KrakenClusterExpansion
}

// krakenClusters implements KrakenClusterInterface
type krakenClusters struct {
	client rest.Interface
	ns     string
}

// newKrakenClusters returns a KrakenClusters
func newKrakenClusters(c *SamsungV1alpha1Client, namespace string) *krakenClusters {
	return &krakenClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the krakenCluster, and returns the corresponding krakenCluster object, and an error if there is any.
func (c *krakenClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.KrakenCluster, err error) {
	result = &v1alpha1.KrakenCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("krakenclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KrakenClusters that match those selectors.
func (c *krakenClusters) List(opts v1.ListOptions) (result *v1alpha1.KrakenClusterList, err error) {
	result = &v1alpha1.KrakenClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("krakenclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested krakenClusters.
func (c *krakenClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("krakenclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a krakenCluster and creates it.  Returns the server's representation of the krakenCluster, and an error, if there is any.
func (c *krakenClusters) Create(krakenCluster *v1alpha1.KrakenCluster) (result *v1alpha1.KrakenCluster, err error) {
	result = &v1alpha1.KrakenCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("krakenclusters").
		Body(krakenCluster).
		Do().
		Into(result)
	return
}

// Update takes the representation of a krakenCluster and updates it. Returns the server's representation of the krakenCluster, and an error, if there is any.
func (c *krakenClusters) Update(krakenCluster *v1alpha1.KrakenCluster) (result *v1alpha1.KrakenCluster, err error) {
	result = &v1alpha1.KrakenCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("krakenclusters").
		Name(krakenCluster.Name).
		Body(krakenCluster).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *krakenClusters) UpdateStatus(krakenCluster *v1alpha1.KrakenCluster) (result *v1alpha1.KrakenCluster, err error) {
	result = &v1alpha1.KrakenCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("krakenclusters").
		Name(krakenCluster.Name).
		SubResource("status").
		Body(krakenCluster).
		Do().
		Into(result)
	return
}

// Delete takes name of the krakenCluster and deletes it. Returns an error if one occurs.
func (c *krakenClusters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("krakenclusters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *krakenClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("krakenclusters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched krakenCluster.
func (c *krakenClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KrakenCluster, err error) {
	result = &v1alpha1.KrakenCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("krakenclusters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
