/*
Copyright 2018 Samsung CNCT.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/samsung-cnct/cluster-controller/pkg/apis/clustercontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKrakenClusters implements KrakenClusterInterface
type FakeKrakenClusters struct {
	Fake *FakeSamsungV1alpha1
	ns   string
}

var krakenclustersResource = schema.GroupVersionResource{Group: "samsung.cnct.com", Version: "v1alpha1", Resource: "krakenclusters"}

var krakenclustersKind = schema.GroupVersionKind{Group: "samsung.cnct.com", Version: "v1alpha1", Kind: "KrakenCluster"}

// Get takes name of the krakenCluster, and returns the corresponding krakenCluster object, and an error if there is any.
func (c *FakeKrakenClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.KrakenCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(krakenclustersResource, c.ns, name), &v1alpha1.KrakenCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KrakenCluster), err
}

// List takes label and field selectors, and returns the list of KrakenClusters that match those selectors.
func (c *FakeKrakenClusters) List(opts v1.ListOptions) (result *v1alpha1.KrakenClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(krakenclustersResource, krakenclustersKind, c.ns, opts), &v1alpha1.KrakenClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KrakenClusterList{}
	for _, item := range obj.(*v1alpha1.KrakenClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested krakenClusters.
func (c *FakeKrakenClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(krakenclustersResource, c.ns, opts))

}

// Create takes the representation of a krakenCluster and creates it.  Returns the server's representation of the krakenCluster, and an error, if there is any.
func (c *FakeKrakenClusters) Create(krakenCluster *v1alpha1.KrakenCluster) (result *v1alpha1.KrakenCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(krakenclustersResource, c.ns, krakenCluster), &v1alpha1.KrakenCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KrakenCluster), err
}

// Update takes the representation of a krakenCluster and updates it. Returns the server's representation of the krakenCluster, and an error, if there is any.
func (c *FakeKrakenClusters) Update(krakenCluster *v1alpha1.KrakenCluster) (result *v1alpha1.KrakenCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(krakenclustersResource, c.ns, krakenCluster), &v1alpha1.KrakenCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KrakenCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKrakenClusters) UpdateStatus(krakenCluster *v1alpha1.KrakenCluster) (*v1alpha1.KrakenCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(krakenclustersResource, "status", c.ns, krakenCluster), &v1alpha1.KrakenCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KrakenCluster), err
}

// Delete takes name of the krakenCluster and deletes it. Returns an error if one occurs.
func (c *FakeKrakenClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(krakenclustersResource, c.ns, name), &v1alpha1.KrakenCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKrakenClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(krakenclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.KrakenClusterList{})
	return err
}

// Patch applies the patch and returns the patched krakenCluster.
func (c *FakeKrakenClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KrakenCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(krakenclustersResource, c.ns, name, data, subresources...), &v1alpha1.KrakenCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KrakenCluster), err
}
